### ISSUE TITLE
Organise the projects under appropriate topics

### ISSUE THREAD

**Issue by Abhinav-26** [Abhinav-26/Machine-Learning-Minor-Projects#2]
Create headings for projects which belongs under particular topic. 
For example - 

Projects related to Computer Vision like (face recognition, face-mask recognition, object detection. etc), shall be added under a new topic as **Computer Vision**.

Similarly, can create sub topic for projects under Machine Learning Fundamentals and add the project within the topics.

**Comment by StreakSharn** [comment]
Hi, I've linked a pull request which organises topics, according to Fundamentals/Advanced, then Regression/Classification/Clustering, then the specific type of algorithm.

For Phone Price Range Detection (ML Fundamentals -> Regression), since the notebook contains 3 different algorithms - Logistic Regression, Decision Tree, and K-Nearest-Neighbour, I haven't put it into any specific folder. Is this okay, or do you think it'd be better some other way?
